### ISSUE TITLE
Failure with numpy 1.18.4

### ISSUE THREAD

**Issue by patatepartie** [gfairchild/pyxDamerauLevenshtein#28]
We're experiencing a bug with `pyxDamerauLevenshtein` 1.5.3 (any version above, and including, 1.5.2, really), when using it with `numpy` 1.18.4 (or any version between 1.18.4 and 1.20.0).

Here's how to reproduce (using docker):
```
docker run --rm -ti python:3.7.6 bash
pip install numpy==1.18.4
pip install pyxdameraulevenshtein==1.5.3
python -c 'from pyxdameraulevenshtein import damerau_levenshtein_distance'
```

This will produce the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "__init__.pxd", line 242, in init pyxdameraulevenshtein
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

This was working fine until at least last Friday, but started failing without any change on our part.

I'm not sure if anything can be done (seems pretty hard to debug), but if someone has the same issue, upgrading `numpy` to 1.20.0+ or downgrading `pyxDamerauLevenshtein` to 1.5.1 works.

**Comment by patatepartie** [comment]
I missed it before, but this seems very similar to #14, although possibly not a duplicate since that bug was fixed.

**Comment by gfairchild** [comment]
Thanks for the issue, @patatepartie. I was able to replicate this. A few things:

1. Note that you're using an old version of this library. 1.6.1 is out. If I try to use NumPy 1.18.4 with it, though, it does still throw an error.
2. I think what I'll do is increase the minimum NumPy version in `setup.py` just to make sure everyone is using a compatible version.

**Comment by gfairchild** [comment]
Ok, I just released a new version of the library (1.6.2) that upped the minimum NumPy version number to 1.19.5. This is passing all CI tests. Can you let me know how this works for you?

**Comment by patatepartie** [comment]
Thank you, @gfairchild .

> Note that you're using an old version of this library. 1.6.1 is out. If I try to use NumPy 1.18.4 with it, though, it does still throw an error.

Indeed. I did try 1.6.1 (all versions between 1.5.0 and 1.6.1, actually) before submitting the issue, but, as you noted, it has the same problem.

> Ok, I just released a new version of the library (1.6.2) that upped the minimum NumPy version number to 1.19.5.

I just tried, using the reproduction steps I listed in this issue (changing the versions to `1.19.5` for numpy and `1.6.2` for pyxDamerauLevenshtein), but it fails with the same error.
It works if I don't install numpy explicitly, as pyxDamerauLevenshtein will install the latest version of numpy which satisfies its requirements, which is currently `1.20.1`.

I think the minimum compatible numpy version should be `1.20.0`, as all versions below that, that I tested, fail.

**Comment by gfairchild** [comment]
> Thank you, @gfairchild .
> 
> > Note that you're using an old version of this library. 1.6.1 is out. If I try to use NumPy 1.18.4 with it, though, it does still throw an error.
> 
> Indeed. I did try 1.6.1 (all versions between 1.5.0 and 1.6.1, actually) before submitting the issue, but, as you noted, it has the same problem.
> 
> > Ok, I just released a new version of the library (1.6.2) that upped the minimum NumPy version number to 1.19.5.
> 
> I just tried, using the reproduction steps I listed in this issue (changing the versions to `1.19.5` for numpy and `1.6.2` for pyxDamerauLevenshtein), but it fails with the same error.
> It works if I don't install numpy explicitly, as pyxDamerauLevenshtein will install the latest version of numpy which satisfies its requirements, which is currently `1.20.1`.
> 
> I think the minimum compatible numpy version should be `1.20.0`, as all versions below that, that I tested, fail.

This is really interesting. I'm not quite sure where the incompatibility comes from. I'm hesitant to require NumPy 1.20.x because [1.20.x dropped support for Python 3.6 and requires 3.7+](https://numpy.org/doc/stable/release/1.20.0-notes.html); I'm trying to maintain compatibility with all currently-supported version of Python (3.6 doesn't hit EOL until the end of this year).

I'm still struggling to understand where exactly the incompatibilities are coming in. I think it has to do with Cython's NumPy integration being tied to specific version numbers, but I can't tell. When I create [`pyxdameraulevenshtein.c`](pyxdameraulevenshtein/pyxdameraulevenshtein.c) (i.e., via `cython pyxdameraulevenshtein.pyx`), my virtual environment has NumPy 1.19.5, so Cython should be making `pyxdameraulevenshtein.c` that relies on that version.

Part of me just wants to remove the NumPy dependency entirely because I'm not sure it's really all that useful in practice; I could pretty easily modify https://github.com/gfairchild/pyxDamerauLevenshtein/blob/master/pyxdameraulevenshtein/pyxdameraulevenshtein.pyx#L165-L180 to just use a `list` rather than `np.ndarray`, and I'm not convinced that performance would be meaningfully different. It seems to me that removing the NumPy dependency would solve multiple headaches.

**Comment by patatepartie** [comment]
> I'm not quite sure where the incompatibility comes from.

The weird thing is that it happened all of a sudden, without anything related (versions of python, numpy or pyxdameraulevenshtein) changing. 
The only thing I can think of is the system packages (build-essential, git, curl, unzip, in our debian-based docker image).

> Part of me just wants to remove the NumPy dependency entirely

I can only speak for our case: numpy is required by many libraries we use, so having to upgrade it is a pretty big risk.
Having one less library depending on numpy lower both the risk of having to upgrade numpy and the risk of breakages when we do have to upgrade numpy.

**Comment by gfairchild** [comment]
Ok, I just completed the transition away from NumPy. The same functionality exists, but it relies on native Python objects (e.g., `list`, `tuple`) rather than NumPy `ndarray` (the methods have been renamed, as indicated in the [changelog](CHANGELOG.md)). This should make the build process much simpler, and there shouldn't be any meaningful performance loss since we weren't actually using NumPy for high-performance array math.

I'm about to push 1.7.0, which will make this change. I'll post once more in this issue once 1.7.0 is live, and then hopefully you can test installing this library to make sure it installs without issue.

**Comment by gfairchild** [comment]
Ok, 1.7.0 is live! @patatepartie, would you mind testing when you have a moment?

**Comment by patatepartie** [comment]
Thank you, @gfairchild 👍🏻 , especially for your responsiveness!

I tested with the reproduction steps above (without installing numpy first), and by running our unit test: everything seems ok.

We can close this issue!
